### ISSUE TITLE
Maximum amount of mods

### ISSUE THREAD

**Issue by kinasch** [linkthehylian/Dying-Light-2-Modding#1]
Hey, first of all thanks for collecting all these guides.

I encountered mods not loading after data7.pak, e.g. data8, data9 and following won't load. I don't know if this is a universal problem though.

**Comment by linkthehylian** [comment]
The pak files have to be in numerical order for the game to be able to side-load them.

![image](https://user-images.githubusercontent.com/20933012/174164426-fba8da96-e9ca-4719-9124-3d61cd6e90e3.png)

I used to have a data3.pak instead of data2.pak after data1.pak and didn't have any issues, that might have gotten changed but I'm not fully sure.

If you could attach a screenshot of what your directory looks like, I'd be able to help further.

**Comment by kinasch** [comment]
![grafik](https://user-images.githubusercontent.com/56368553/174169211-25088c4c-7b99-4518-b35a-75a54507c803.png)

I know about the ascending order of dataX.pak, I meant to say that everything after data7.pak does not load for me.
But thank you very much for the tip and fast answer.
I had a data8.pak here and its content was not loaded in the game. After posting this issue, I just put multiple mods in one dataX.pak, that's probably what you did in the screenshot :D.

**Comment by linkthehylian** [comment]
My guess would be that whatever's being side-loaded from your data7.pak possibly has incorrect directory pathing? Might be why it's not reading anything after that one. Always a good idea to check that just in case.

**Comment by kinasch** [comment]
Thanks a lot for your ideas. Personally I just try to keep the X in dataX.pak below 8.
Closing the issue, as it's kinda not really an issue. Was probably due to my error anyways.
